### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jozzan** [adferrand/docker-letsencrypt-dns#1]
Since I really appreciate the effort. I just wanted to let you know that there might me a mistake in your documentation. As it always says: "LEXICON_CLOUDFLARE_USER". Yet, it wants: "LEXICON_CLOUDFLARE_USERNAME", configured. At least that was for me the case.

**Comment by adferrand** [comment]
You are totally right. It is indeed LEXICON_CLOUDFLARE_USERNAME, I forgot to correct it in the README.md. It is done now.

Regards,
Adrien Ferrand
