### ISSUE TITLE
Support Cert Fileout names to be configurable.

### ISSUE THREAD

**Issue by oliverkane** [adferrand/docker-letsencrypt-dns#16]
Hi there, I'd like to be able to customize the naming convention your certs are deployed.  Currently the format seems to be:

```
/etc/letsencrypt/live/$domain/cert.pem 
```

In my setup, (I'm using https://github.com/jwilder/nginx-proxy), it expects a mounted volume using the format

```
/etc/nginx/certs/$domain.pem
```

If this was configurable, these two images would be compatible and I can build out something akin to https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion.  

If not, my goal would be to fork this repo and modify these places. Would that be sufficient or are there other gotchas I need to be aware of?
https://github.com/adferrand/docker-letsencrypt-dns/search?q=.pem&unscoped_q=.pem

**Comment by adferrand** [comment]
I think it is possible pretty easily. Indeed, there is a directory named renew-hooks under /etc/letsencrypt, with three subfolders : deploy, pre and post. Any executable in theses folders will be executed by certbot at the relevant step of the renew process.

So you can just put a script to rename the renewed certificates accordingly to the pattern you need. Env variables will be passed to know which certificate is renewed, you can check the documentation of certbot about hooks for that.

**Comment by oliverkane** [comment]
Awesome. I'll check into that and see what I can cobble together.

**Comment by adferrand** [comment]
Any news?

**Comment by aliocha** [comment]
Same problem for me. @oliverkane , did you get it working? I have exactly the same need with the same docker image (https://github.com/jwilder/nginx-proxy). If i can avoid to fork it ...

**Comment by oliverkane** [comment]
Sorry ya'll. I ended up getting involved in a different project.  We're looking at Kubernetes rather than docker, and are waiting for this Issue to get resolved.  It's pretty active of late.

https://github.com/jetstack/cert-manager/pull/345

**Comment by adferrand** [comment]
OK. In the mean time @aliocha, you can code your own shell scripts hooks to move the certificates to a new path. Scripts need to be in `/etc/letsencrypt/renewal-hooks/deploy` and will be run in alphabetical order. They will be persisted, as `/etc/letsencrypt` is declared as a volume in my docker.

You need only to take on think into account. I declared on command line a deploy hook script, that will be executed **after** any script lying in `/etc/letsencrypt/renewal-hooks/deploy`. It is only to fix some file permissions and optionally generate PFX. Nothing you need. or everything that can be done by your own script. But to avoid the hook to fail, copy the files, to not move them.
