### ISSUE TITLE
Domains.conf file and accessibility to certificates

### ISSUE THREAD

**Issue by TaylorChristie** [adferrand/docker-letsencrypt-dns#18]
I'm having a couple issues with you container (although it is quite awesome).

1. I've added two lines to the domains.conf file: 
```
*.d.com d.com
*.a.d.com a.d.com
```

Only the first line is being run. Am I missing something or can i do nested subdomains with this certificate?

2. I cannot access the certificates without `sudo chown -R 1000:1000 *` on the mounted folder even though i passed 
```
      - CERTS_DIR_MODE=0755
      - CERTS_FILES_MODE=0644
```
into the docker-compose environment vars.

**Comment by adferrand** [comment]
For the first issue, I am pushing a correction: in some situations, last line could be skipped if the file does not finish with a new line.

**Comment by adferrand** [comment]
For the second issue, it is because the environment variable is `CERTS_DIRS_MODE`, not `CERTS_DIR_MODE`.

**Comment by adferrand** [comment]
Version 2.2.0 released !
