### ISSUE TITLE
Does docker-letsencrypt-dns support testing api?

### ISSUE THREAD

**Issue by grapehunter** [adferrand/docker-letsencrypt-dns#25]
LetsEncrypt has rate limit. https://letsencrypt.org/docs/rate-limits/
Can I use stage api to test?

**Comment by adferrand** [comment]
Yes of course. My container has an environment variable which toggles the use of the staging api instead of the production one. You can check README.md for that.

**Comment by grapehunter** [comment]
@adferrand Got it. Thank you very much.
