### ISSUE TITLE
Cannot use *.example.com example.com in a single line

### ISSUE THREAD

**Issue by d4rk22** [adferrand/docker-letsencrypt-dns#26]
When trying to use *.example.com example.com on a single line in domains.conf the letsencrypt-dns docker container complains of "sh unknown operand" in the logs and doesn't create any certificates. Should be easy to reproduce but if you need any more details let me know. I'm just using a work around in the mean time.

[docker-compose.yml](https://gist.github.com/d4rk22/4faed5fba5c5ffcfc490a4b4676af75b)

**Comment by d4rk22** [comment]
I've uploaded the file [here](https://dsh.re/f4fa4).

**Comment by adferrand** [comment]
OK. I could reproduce the bug, and build a new version (2.5.1) with a correction. Can you confirm it is working for you now ?

**Comment by d4rk22** [comment]
This fixed my issue. Thank you!
