### ISSUE TITLE
Restart Apache Outside a Container?

### ISSUE THREAD

**Issue by pprotschka** [adferrand/docker-letsencrypt-dns#28]
thank you for this little gem. Works like a charme!
how would i best go about reload apache outside a container (on the host bare bones machine)...

basically id need the docker to run "systemctl apache2 reload" on the host after a certificate has been renewed or created. 

any help is appreciated.

Thank you.

**Comment by adferrand** [comment]
Hello! This will be quite hard, as containers are essentially designed to isolate the container from the host, so you are trying to break this security in fact.

Strictly speaking, to make it work, you could have another container with a ssh client available, and able to connect to the host by RSA authentication, and ask my container to execute the remote command from this container. 

But in terms of architecture, if you have already a Docker system running on your host to handle certificates through my container, you should also dockerize your apache, which is a really well documented operation, and you will be able to use my autocmd-containers functionality.
