### ISSUE TITLE
Merge private key and cert to PFX file after renewal

### ISSUE THREAD

**Issue by elcattivo** [adferrand/docker-letsencrypt-dns#3]
Your container is working perfectly fine with services that use separate private key and cert files. Unfortunately I also have a service that requires a PFX file. How would you approach this problem and automate the merge process after each renewal?

**Comment by adferrand** [comment]
In theory you can put hooks scripts files in /etc/letsencrypt/renew/deploy, which will be called for each certificate renew. You have access to openssl utility inside the container, so you can convert to any format.

However, this external approach will not fit very well. You would need also to ensure the conversion for new certificate creation.

Best approach is to rebuild the Docker with convenient scripts for each certificate life cycle step.

But I did it for you. I think pfx format is quite common, in particular for non-Web services, which are the target of my container. So version 1.3.1, pushed yesterday, can use the EXPORT_PFX environment variable to toggle pfx conversion. See the README.md for more information.

Regards,
Adrien Ferrand

**Comment by elcattivo** [comment]
Thank you.
