### ISSUE TITLE
Add configurable delay?

### ISSUE THREAD

**Issue by loganto** [adferrand/docker-letsencrypt-dns#30]
My DNS registrar (namesilo) doesnt push updates immediately but instead on 5 minute intervals.  
This causes certs not generate as script times out.  
Is there a way to handle this? is there some option to delay DNS record check to 5 minutes?

**Comment by adferrand** [comment]
Yes of course. The environment variable `LEXICON_SLEEP_TIME` is made for that. See https://github.com/adferrand/docker-letsencrypt-dns/blob/master/README.md#sleep-time

**Comment by loganto** [comment]
Ohh awesome! Thank you I missed that.
