### ISSUE TITLE
domains.conf does not issue certificate for other than line 1

### ISSUE THREAD

**Issue by mirzawaqasahmed** [adferrand/docker-letsencrypt-dns#42]
Hi Adrien,
First of all thank you very much for this wonderful project.

I am trying to set this up in my environment and seeing that any line after the first line is not getting certificates issued? I have gone through some closed issues and understand that new-line was may be not dealt properly but then those issues were fixed.
My domains.conf for now has simple 3 entries.

```
bigip-ve-2.domain.net
bigip-ve-1.domain.net
bigiq-ve-1.domain.net
```
everything works for first line. but the second one does not get issued.

Any idea?

**Comment by mirzawaqasahmed** [comment]
this worked. closing now.
it took a bit of time around 5 min but got it in the end.

**Comment by adferrand** [comment]
Hello @mirzawaqasahmed! Just to know, what is the solution you used? Could something be improved on my container?
