### ISSUE TITLE
REQ: Per-key directories

### ISSUE THREAD

**Issue by westurner** [adferrand/docker-letsencrypt-dns#43]
Would it be possible to store keys in per-domain (+SANs) directories named with the primary domain? That way containers would only have access to the keys in that specific directory.

(I've only just read the README, so maybe this is already least necessary privilege?)

**Comment by adferrand** [comment]
Hello @westurner! I am really sorry that I took so much time to respond, I was quite occupied with the upstream projects that are used in my docker, for which I am part of the dev teams. 

So about your request, the layout used here is the one that is generated by Certbot, and Certbot relies on it to behave correctly. So modifying how the keys are store would break its behavior. 

However, thanks to #45, you can execute now any logic you want using a dedicated script that will be execute upon each certificate creation or renewal. 

So I think the best you should do here is writing a script to compose the layout in a separate directory from `/etc/letsencrypt`, and use it instead. 

I think in the future to propose some pre-built deploy scripts that matches common needs here. 

I will close the issue, but if you have any further question or potential improvement to propose, do not hesitate to respond.
