### ISSUE TITLE
Merging the cluster_config branch

### ISSUE THREAD

**Issue by charleszlu** [adferrand/docker-letsencrypt-dns#46]
Is the cluster_config branch containing PR #15 able to be merged into the master branch? Autorestarting of docker swarm services would be very useful.

**Comment by charleszlu** [comment]
I have just realised that the same thing could be achieved by using the `DEPLOY_HOOK` environment variable like: `DEPLOY_HOOK="docker service update --quiet --force <service name 1>; docker service update --quiet --force <service name 2>"`

**Comment by adferrand** [comment]
Yes you can. But in this case, the reload is done for any domain on one specific service. If you want to do it per domain and service basis, you need to use something else.

I am in fact working on the autorestart support on swarm, it will be here soon.

**Comment by adferrand** [comment]
I just release 2.14.0: it includes the autorestart on Swarm feature.

**Comment by charleszlu** [comment]
Thanks. Can confirm it works well.
