### ISSUE TITLE
Issues starting container

### ISSUE THREAD

**Issue by ActualPlayer** [adferrand/docker-letsencrypt-dns#72]
No matter what combination of configuration options I try, I can't get the container to start.

Using the docker-compose file in the repository I tried to get certificates for my cloudflare domain.

First I tried to create the composer file myself, but after not getting it to launch I used the composer file in the repository with the same result.

my domains.conf file has one line in it with the correct domain ofcourse: 

`*.mydomain.com mydomain.com`

When looking at the logs of the container I see one line repeated over and over:

`standard_init_linux.go:211: exec user process caused "exec format error"`

then the container restarts and gives me the same error and no further information.

How can I debug this better or what causes this error?

**Comment by adferrand** [comment]
I suspect your try to start in a ARM machine like a Raspberry. Is it the case?

**Comment by ActualPlayer** [comment]
Yes that is correct.

**Comment by adferrand** [comment]
OK, I am sorry, images are available for amd64 only for now. I am working on it, but it will take some time.

As an immediate mitigation, you can checkout my repo, and build the Docker from sources on your machine.

**Comment by ActualPlayer** [comment]
Okay thank you for the response.

**Comment by ActualPlayer** [comment]
Just going to post one last comment here on how I did it to help anyone else with the same issue:

Clone the git repository and change the dockerfile so it says at the top:

`FROM arm32v7/python:3.8-alpine3.11`

Afterwards you can build on a raspberry pi. Unfortunately my pi (3) ran out of memory in the building process so I had to build the image on an ubuntu machine. Since you can't normally build ARM images on non-ARM machines I had to follow this guide to do that:

https://matchboxdorry.gitbooks.io/matchboxblog/content/blogs/build_and_run_arm_images.html

For some reason this did not work on Ubuntu 19.10 and I had to go to a 18.04 machine.

Building process took a while but afterwards I could package my image, transfer it to my pi and load it up.

**Comment by patrickpissurno** [comment]
Hi! For future readers, please take a look at [my fork](https://github.com/patrickpissurno/rpi-docker-letsencrypt-dns). It's an automated multiarch build of this image supporting amd64, arm64 and armhf (armv7).

An up-to-date version of the [upstream source code](https://github.com/adferrand/docker-letsencrypt-dns) is fetched, built and released in my [Docker Hub](https://hub.docker.com/r/patrickpissurno/rpi-docker-letsencrypt-dns) daily (automated via [Travis CI](https://travis-ci.org/patrickpissurno/rpi-docker-letsencrypt-dns/)).

You just have to replace every `adferrand/letsencrypt-dns` occurrence with `patrickpissurno/rpi-docker-letsencrypt-dns`.

Give it a try!

**Comment by adferrand** [comment]
Good initiative! I will soon publish a major refactoring of the Docker, that will require some modifications on your side (but making it even simpler I think). Once done, would you like to submit a PR of your work on my repo?

**Comment by adferrand** [comment]
Aaaand I answered to fast. Did not see that you already submitted the PR ^^

**Comment by patrickpissurno** [comment]
Yeah, I'm quite interested in bringing arm support to the mainline image.

I'd like to discuss how we can do that, but I think it'd be more appropriate if we did that in the PR itself #77 (just to make the discussion more visible for other contributors).

**Comment by Neejoh** [comment]
Wow, took me longer to find this issue than I'm comfortably with telling. 
New to Docker so everything takes a bit longer than I initially think it will.

Anyway, I too wanted to run this on a Raspberry Pi (4B, arm7).

The fork by @patrickpissurno is for _docker-letsencrypt-dns_, not _dnsrobocert_, does that matter? I think it is automatically migrated even though the upstream is renamed?
