### ISSUE TITLE
Wildcard certificates

### ISSUE THREAD

**Issue by elcattivo** [adferrand/docker-letsencrypt-dns#8]
As Let's [Encrypt now supports wildcard certificates](https://community.letsencrypt.org/t/acme-v2-production-environment-wildcards/55578), adding this feature to docker-letsencrypt-dns might be a good idea. In order to request wildcard certificates, _ACME v2_ must be used. The [minimum required version](https://letsencrypt.org/docs/client-options/#acme-v2-compatible-clients) of certbot, that can use the new endpoint, is _0.22.0_.

**Example command:** `./certbot-auto certonly --manual -d *.example.com -d example.com --preferred-challenges dns-01 --server https://acme-v02.api.letsencrypt.org/directory`

Source: https://community.letsencrypt.org/t/getting-wildcard-certificates-with-certbot/56285

**Comment by adferrand** [comment]
Indeed, I also saw the announcement yesterday. It will be implemented tomorrow!

**Comment by elcattivo** [comment]
Thank you.
