### ISSUE TITLE
Cert automatically deleted

### ISSUE THREAD

**Issue by clementblaise** [adferrand/docker-letsencrypt-dns#9]
Hello,

After the cert has been successfully generated, it's directly deleted from what I see on the log.
The cert is not in the live dir when using a wildcard domain on ovh while a sub-domain work perfectly.

**Comment by adferrand** [comment]
I will check that tomorrow. Sorry for the bug.

**Comment by adferrand** [comment]
Hello, I published a new version (2.0.1) which fixes this issue.

**Comment by clementblaise** [comment]
Hello 2.0.1 fixed the problem thank you for your reactivity and great work btw :)
